server:
  port: 9002

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
